### ISSUE TITLE
Mqtt parsing error for device

### ISSUE THREAD

**Issue by bpsphere** [casanet/casanet-server#305] opened 2024-08-30 05:01 UTC
I have a temperature sensor which I want to set a value.
The server is running on Rpi-5

# Dash Looks like this
![image](https://github.com/user-attachments/assets/e0a68991-deb9-4ddd-8f2a-cd9029ad18c2)

```
this the received message by mosquitto local broker.

casanet/state/mXILTy {"temperatureSensor":{status":"on","temperature":20}}

```
And the error message looks like this

```[8/30/2024, 14:49:04] [error] [MqttHandler.onMessage] Parsing mqtt message for casanet/state/mXILTy:{"temperatureSensor":{status":"on","temperature":20}} failed, error: {}```

**Comment by haimkastner** [comment] 2024-09-05 07:46
Hi @bpsphere 

I have reproduced the issue in my environment, which seems to be a backend issue.
I have transferred it to the server repo.

You can pull the latest version ([4.0.45](https://github.com/casanet/casanet-server/releases/tag/4.0.45)) including the fix.

**Closed by haimkastner** 2024-09-05 07:46 UTC

**Comment by bpsphere** [comment] 2024-09-09 07:00
Thank you so much, appreciate you effort
